---
name: CI

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest UReport version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: rapidpro/ureport
          prefix: 'v'
        id: ureport_version

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            onaio/ureport:latest
            onaio/ureport:${{ steps.ureport_version.outputs.tag }}
          build-args: |
            UREPORT_VERSION=${{ steps.ureport_version.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
