---
name: CI

on:
  workflow_dispatch:
    inputs:
      ureportVersion:
        description: 'UReport Version'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            onaio/ureport:latest
            onaio/ureport:${{ github.event.inputs.ureportVersion }}
          build-args: |
            UREPORT_VERSION=${{ github.event.inputs.ureportVersion }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
